"""Add is_recursive to AllowedDirectory

Revision ID: 615767d4c79d
Revises: 4e8d1ea42c8a
Create Date: 2024-11-29 14:00:40.034769

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "615767d4c79d"
down_revision = "4e8d1ea42c8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allowed_directory", schema=None) as batch_op:
        batch_op.alter_column(
            "is_recursive", existing_type=sa.BOOLEAN(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allowed_directory", schema=None) as batch_op:
        batch_op.alter_column("is_recursive", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
