"""Add description and is_recursive fields to models

Revision ID: 7a5afde255a5
Revises: 040911525030
Create Date: 2024-11-29 00:33:18.956264

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a5afde255a5"
down_revision = "040911525030"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allowed_directories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("is_recursive", sa.Boolean(), nullable=True))

    with op.batch_alter_table("api_endpoints", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))

    with op.batch_alter_table("persistent_variables", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("persistent_variables", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("api_endpoints", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("allowed_directories", schema=None) as batch_op:
        batch_op.drop_column("is_recursive")
        batch_op.drop_column("description")

    # ### end Alembic commands ###
