"""Add reference system models

Revision ID: a1a9de0b0fbd
Revises:
Create Date: 2024-11-28 20:00:06.579948

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1a9de0b0fbd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("has_references", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("last_reference_update", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("reference_status", sa.String(length=50), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fence", schema=None) as batch_op:
        batch_op.drop_column("reference_status")
        batch_op.drop_column("last_reference_update")
        batch_op.drop_column("has_references")

    # ### end Alembic commands ###
