"""Add type field to APIEndpoint

Revision ID: be2d7790f4b2
Revises: 615767d4c79d
Create Date: 2024-11-29 15:09:39.656016

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be2d7790f4b2"
down_revision = "615767d4c79d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_endpoint", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type", sa.String(length=50), server_default="unknown", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_endpoint", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
